CREATE TABLE USERINFO 
(
  USERID NUMBER(20) NOT NULL 
, NAME VARCHAR2(200) 
, PNO NUMBER(13) 
, EMAIL VARCHAR2(50) 
, DOCUMENT VARCHAR2(500) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    USERID 
  )
  ENABLE 
);
